
project_id = "hzqnccsmejplilhmisgu"

[functions.device-status-monitor]
verify_jwt = false
no_cache = true
import_map = "import_map.json"

[functions.schedule-device-monitoring]
verify_jwt = false
no_cache = true
import_map = "import_map.json"
