// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmnopirdysucmxwgyezo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtbm9waXJkeXN1Y214d2d5ZXpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMTI4MTUsImV4cCI6MjA2MDU4ODgxNX0.yNVC1bAivh1nNzdHx6KaxZt4KyAgJBa5uOwhhNGXJEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);